### ISSUE TITLE
How does this compare to railwaycat/homebrew-emacsmacport?

### ISSUE THREAD

**Issue by nwolfe** [d12frosted/homebrew-emacs-plus#1]
I came across this repository from the [Spacemacs#develop installation instructions](https://github.com/syl20bnr/spacemacs/tree/develop#os-x), which I noticed recently changed from recommending https://github.com/railwaycat/homebrew-emacsmacport to this.

What's the difference between this and that?

The Spacemacs instructions only mention that this provides a Spacemacs icon, yet emacs-mac has `--with-spacemacs-icon` (at least it did last time I installed it).

I'm happy to use this repo, just wanted to understand which of the two might be better choices going forward.  I know that you're involved in Spacemacs, so perhaps this emacs distribution might have a better chance at alignment with Spacemacs?

**Comment by d12frosted** [comment]
Emacs Mac Port is GNU Emacs plus some additions for OS X (mostly related to GUI, AFAIK). These additions are made on the Emacs source level. So it's not really GNU Emacs anymore. Also you are tided to Emacs Mac Port version.

Emacs Plus is just plain GNU Emacs with some additions on formulae level (at least for now). Currently it only gives you an option to install Emacs with Spacemacs icon. And you are free to install Emacs 24 or Emacs 25 via this formulae (just like with plain `emacs`). 

So basically, we switched from Emacs Mac Port recommendation to GNU Emacs. We just wanted to give users option to install Emacs with Spacemacs icon. Since we didn't want to confuse anyone with Spacemacs distribution of Emacs, we named it 'emacs-plus'. 

Some useful references: 

- https://github.com/syl20bnr/spacemacs/issues/4955 (discussion about GNU Emacs vs Mac Port)
- https://github.com/syl20bnr/spacemacs/pull/5161
- https://github.com/syl20bnr/spacemacs/commit/fa5e66c799e74325fbd513cdfa9348b53e023491#commitcomment-16933870
- https://github.com/syl20bnr/spacemacs/pull/5655,

**Comment by nwolfe** [comment]
Ahhh, I see now! Thank you for the explanation. I remember seeing the first link/issue come through Spacemacs now that I think about it.
I've been experiencing the issues mentioned with emacsmacport, so I'm going to give emacs-plus a shot for some time!

**Comment by d12frosted** [comment]
> so I'm going to give emacs-plus a shot for some time

For now you are just giving a shot to GNU Emacs 😛 

> move to README

Good idea.

**Comment by d12frosted** [comment]
@nwolfe if you wish to add anything to README - you're welcome to send pr 😄

**Comment by srustamo** [comment]
I'm seeing a slight difference in font rendering compared to `emacs-mac`. Screenshot shows. Fonts are in `emacs-plus` rendered wider, all things being equal. Any idea why?
![scr](https://cloud.githubusercontent.com/assets/749813/25435072/422cf45e-2aa8-11e7-803f-6f02e689a1b4.jpg)

**Comment by srustamo** [comment]
The screenshot on the left is `emac-mac`.
Both use `(set-face-attribute 'default nil  :family "Hack")` in `init.el`
