### ISSUE TITLE
Railwaycat emacs-mac support

### ISSUE THREAD

**Issue by avendael** [d12frosted/homebrew-emacs-plus#10]
In my experience, [railwaycat emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport) is the best emacs to use in a mac. It has smooth scrolling and touchpad gesture support among other things. It would be awesome if there's an option that would install the railwaycat version instead of the cocoa version.

**Comment by d12frosted** [comment]
Good idea. I think it should be separate formulae named `emacs-mac[-port]-plus`, because I don't really want to merge two different formulas. What do you think?

**Comment by SteveJobzniak** [comment]
@d12frosted I have switched to emacs-mac. Much more responsive. Less crashes. Nicer GUI.

It's literally GNU Emacs + patches on top. So it is as-up-to-date as the official repo.

It has SVG built-in via WebKit.

All you need to do is enable all these features (yes all of them, some packages require texinfo and xm2):

```
  brew tap railwaycat/emacsmacport
  brew install emacs-mac --with-gnutls --with-imagemagick --with-modules --with-texinfo --with-xml2 --with-spacemacs-icon
  brew linkapps emacs-mac
```

I also suggest updating the osx layer for Spacemacs to disable smooth scrolling in this Emacs fork, because it's more like a tech-demo/hack. It probably emulates keyboard scrolling, draws a texture and tries to smoothly insert it. In reality is choppy as hell.

```emacs-lisp
  ;; GUI Settings for YAMAMOTO Mitsuharu's Mac port of GNU Emacs.
  ;; https://github.com/railwaycat/homebrew-emacsmacport
  (when (and (spacemacs/system-is-mac) (display-graphic-p))
    ;; Disable pixel-by-pixel scrolling, since it's extremely choppy.
    (setq mac-mouse-wheel-smooth-scroll nil))
```

**Comment by SteveJobzniak** [comment]
Oh and that fork also AWESOMELY bug-fixes sRGB rendering of XMP bitmaps, which means that Powerline no longer looks like trash.

My config now looks like this:
```emacs-lisp
  ;; Switch powerline separators to text, since the bitmaps look bad in sRGB.
  ;; It's possible to disable sRGB, but that makes Emacs colors too bright.
  ;; (setq powerline-default-separator 'utf-8)
```

;-)

**Comment by SteveJobzniak** [comment]
There is no reason to ever use the old emacs/emacs-plus. They are garbage compared to railwaycat. He's had a reputation for years as the best port, and it's true.

**Comment by d12frosted** [comment]
@SteveJobzniak I am glad for you. Thanks for sharing your thoughts about GNU Emacs vs `emacs-mac-port`. 

> They are garbage compared to railwaycat. He's had a reputation for years as the best port, and it's true.

Many people (including me) switched to GNU Emacs from `emacs-mac-port` just because the latter was so very laggy and low-peformance that it was just unusable. I should check how it runs nowadays. 

> Oh and that fork also AWESOMELY bug-fixes sRGB rendering of XMP bitmaps

That's great. And the fix was there for a long time. For me powerline separator is even not an issue compared to performance. 

But as I said - I'll give it a try to see how it runs after switch to Emacs 25.

**Comment by SteveJobzniak** [comment]
@d12frosted The performance of emacs/emacs-plus had lots of random freezes and those are totally gone with emacs-mac. Others have said the same. Railwaycat's changelogs make it seem like he has implemented better polling.

And just disable the silly pixel-by-pixel scrolling (which IS slow as hell and chopy). After that is disabled, I notice only improvements compared to vanilla.

**Comment by d12frosted** [comment]
> Others have said the same.

I don't know anyone except for you saying this. But welp, we are word-comparing different versions of software. And just in case you didn't see it - https://github.com/syl20bnr/spacemacs/issues/4955. 

> But as I said - I'll give it a try to see how it runs after switch to Emacs 25.

Only after I check it myself I can say anything about latest `emacs-mac-port`.

**Comment by SteveJobzniak** [comment]
http://emacs.stackexchange.com/a/3952/14218

> I have tried all of the above options (even the tap recommended by Reiner in a comment above) by none have worked well for me (trackpad scrolling problems, hangings, etc.). I am quite happy, however, with Yamamoto Mitsuharu's fork, as mantained by railway's github page. It is up-to-date with respect to the official GNU version.

Just one of many comments I found like that. Reddit was also full of comments like that when I did research.

And yeah try it out. Either way, I am running it now and will never go back. So far I haven't had a single freeze or crash anymore.

**Comment by SteveJobzniak** [comment]
Well, I just had a 5 hour session without any hangs, slowdowns or crashes. That's in comparison to the emacs/emacs-plus vanilla version which crashed constantly. On the exact same dotspacemacs file and same develop branch of Spacemacs.

**Comment by d12frosted** [comment]
Well. I am using it for 5 minutes and already run into some lags / slowdowns. I know that it's not the best way to navigate, but sometimes I hold `C-n` or `C-p` to go down / up over the lines. And almost every time I do it `emacs-mac-port` starts to freeze and cursor disappears for a second or so. 😞 

But lets see how it goes with other tasks 😸

**Comment by SteveJobzniak** [comment]
@d12frosted I opened my init.el (~900 lines) and helt down C-n and then C-p for about 2 minutes, not even a single missing cursor or freeze. Could it be a hardware issue on your machine? A bug that only affects yours?

**Comment by SteveJobzniak** [comment]
@d12frosted 
Maybe try this:

```emacs-lisp
  ;; GUI Settings for YAMAMOTO Mitsuharu's Mac port of GNU Emacs.
  ;; https://github.com/railwaycat/homebrew-emacsmacport
  (when (and (spacemacs/system-is-mac) (display-graphic-p))
    ;; Disable pixel-by-pixel scrolling, since it's extremely choppy.
    (setq mac-mouse-wheel-smooth-scroll nil))
```

See if that improves your `C-n` and `C-p` situation.

I run with it off. Perhaps that's it.

**Comment by d12frosted** [comment]
It's the same with `mac-mouse-wheel-smooth-scroll` set to `nil` and set to `t`.

**Comment by SteveJobzniak** [comment]
@d12frosted Hmm okay. That's weird.

I've now spent all day coding in emacs-mac. Not a single crash or slowdown yet. Even the small "stutters" I used to get when using the space-menu are gone.

With emacs (the vanilla one via your emacs-plus formula) I had about one total hang every 1-2 hours with the GUI using 100% CPU and not being rescuable with Ctrl-g.

That really shows how different experiences can be. I have no idea why this one works worse for you but much better for me. Very weird.

**Comment by ninrod** [comment]
@SteveJobzniak I build emacs from source (git HEAD) and I never experience a hang. it's my main editor for everything except java.

**Comment by fuxialexander** [comment]
@d12frosted @SteveJobzniak I've tried both emacs vanilla and emacs-mac. The problem of emacs-mac for me is: when you use the native fullscreen on mac and you want to switch using touchpad between different fullscreen apps, say, emacs-mac and safari, there is a significant lag. Vanilla Emacs do not have that problem.

**Comment by bassu** [comment]
@SteveJobzniak You're right. The default smooth scrolling in @railwaycat's `emacs-mac` port is really choppy. I am not sure why others find it pleasing. Your tweaks returned back the sanity without having me go through gazillion lines of scroll documentation. 👍

**Comment by SteveJobzniak** [comment]
@ninrod I have now used railwaycat's Emacs for a month and have zero hangs. I haven't tried regular Emacs HEAD, maybe that would also have solved the hangs I was having.

@fuxialexander Yes railwaycat uses native fullscreen which has an entry/exit animation and disables all input (Apple does) while it animates. But I never use fullscreen.

@bassu Yeah it blows my mind why anyone likes the choppy default mess, but probably because they used regular Emacs scroll before that which scrolls way too fast. Hence why I tweaked it to scroll less lines at a time. Glad my tweaks helped you! :-)

**Comment by d12frosted** [comment]
Ok, I have played with `emacs-mac-port` for a while and still think that it doesn't fit my needs. Mostly because it solves issues that I personally don't care about while adding some strange input lags and freezes, adding some strange issues with server (it's not reliable anymore) and forces me to change how I launch emacs (not a simple `emacs` in the terminal anymore). This is not objective, I know. Rest assured that it doesn't affect my view on the subject, it just affects my tool set 😸 

What I am going to do is to update Spacemacs installation guide for macOS users with a note about `emacs-mac-port`. Some people might find it more pleasant. I would be really happy if people experiencing issues with GNU Emacs could solve them either by someone fixing bugs in GNU Emacs or just switching to Emacs Mac Port. 

Thanks everyone for a good discussion on this topic. I really appreciate your effort. And thanks for the hints about scrolling (for some reasons I like line-by-line scrolling even if I use touchpad 😸 ).

To be honest I am not sure if there is a point in having `emacs-mac-port-plus` formulae as the features provided by `emacs-plus` are either available in `emacs-mac-port` (e. g. Spacemacs icon) or don't make much sense with mac port version (e. g. `-x11` option). Since `emacs-mac-port` formulae authors are more open to new features I'd rather contribute directory to them new features (like 'borderless support'). 

Just as a history notice, `emacs-plus` was created simply because I wanted to provide Spacemacs users ability to install GNU Emacs with Spacemacs icon (despite the fact that I **don't** use it 😸 ). Homebrew maintainers are agains such additions to `emacs` formulae so I had to create my own tap. The name `emacs-plus` was chosen intentionally (it has several purposes) and as it turned out, it's a good name. Recently hombrew maintainers made `emacs` formula 'obsolete' as they now promote cask version (installed via `brew cask install emacs`) over regular (installed via `brew install emacs`). Then they throw away X support. That's not a great list of 'features', but anyways 😸 

So as you can see, `emacs-plus` is about GNU Emacs. In case it get's something useful for mac port, I'll try to contribute to that project as well. 

That being said, I am closing this issue. Thanks again everyone for the input and feel free to continue your discussion here.
