### ISSUE TITLE
--with-xwidgets flag appears to be broken

### ISSUE THREAD

**Issue by agzam** [d12frosted/homebrew-emacs-plus#162]
can't build from --HEAD --with-xwidgets

**Comment by d12frosted** [comment]
Hey, please see #161. Closing this as duplicate :)

**Comment by agzam** [comment]
@d12frosted I don't think it is a duplicate though. It doesn't work with or without imagemagick.

```
2 out of 33 hunks FAILED -- saving rejects to file src/xwidget.c.rej
patching file src/xwidget.h
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/emacs-plus--patch-20191227-86448-iov3u1/xwidgets_webkit_in_cocoa.patch` exited with 1.
```

**Comment by d12frosted** [comment]
Oh @agzam sorry, for some reason I've read xwidgets as imagemagick! I will take a look later. It's shame that it doesn't work.

**Comment by d12frosted** [comment]
@agzam since I moved to GitHub workflows, I am going to add build test for xwidgets options. It doesn't fix the issue per se, but at least improves the visibility on when it breaks 😸 Also in the same PR (#166) I am trying to fix the build. The build passed, but I didn't test it on my machine (e.g. I didn't run to verify if it works). I will test it shortly.

And I want to setup a repository for myself to ease support of all patches (including the xwidget), because right now it's so chaotic and random.

**Comment by d12frosted** [comment]
Ok, I verified that it works. So merged that fix. Let me know if it works or doesn't work 😸 

And @agzam thank you for staying with `emacs-plus` for such a long time 😸
