### ISSUE TITLE
Command/alt switch

### ISSUE THREAD

**Issue by t-hart** [d12frosted/homebrew-emacs-plus#178]
When running emacs-plus, it seems to switch my cmd/alt keys from what I expect. I'm used to running `cmd-x` for `M-x`, but with emacs-plus I need to `alt-x`. This is not the case with the other version of Emacs I've got installed (Railwaycat). 

I don't know whether this is something that their version changes or that emacs-plus takes care of, but would  it be possible to reverse?

I tried looking through their [feature list](https://bitbucket.org/mituharu/emacs-mac/src/f3402395995bf70e50d6e65f841e44d5f9b4603c/README-mac?at=master&fileviewer=file-view-default), but couldn't find anything mentioning this.

**Comment by d12frosted** [comment]
It's because `M` in `M-x` stands for meta key. On modern keyboards we don't have separate key for that so many applications (including Emacs) use Alt as Meta. It's debatable, but the good part is that we are in the Emacs world, were you can make a choice by yourself.

```emacs-lisp
(setq mac-option-modifier nil
        mac-command-modifier 'meta)
``` 

Note that it makes sense to set this only on macOS and only when outside of terminal.

```emacs-lisp
(when (and (eq system-type 'darwin) (display-graphic-p))
  (setq mac-option-modifier nil
        mac-command-modifier 'meta))
```

Hopefully that helps.

P. S. Also keep in mind that `emacs-mac` has many modifications to GNU Emacs. Fundamentally, `emacs-plus` is a build script for GNU Emacs with minor modifications. Things that dramatically change defaults or change them in questionable ways are not enabled by default. And `emacs-plus` generally doesn't change the stuff that can be configured from `init.el` file.

**Comment by t-hart** [comment]
Gotcha! Yeah, I found a corresponding bit of code in the spacemacs OSX layer:
```elisp
  (when osx-swap-option-and-command
    (cl-rotatef mac-command-modifier mac-option-modifier))
```
I'm aware that it's not the standard, it's just always worked that way on macOS for me (I suppose I just always used emacs-mac so never had to deal with it). Mapping command to Meta in Emacs makes it act more like it does in Linux in terms of key positioning and the like. 

Thanks  for the snippet, though! Any reason you wouldn't use that modification inside a terminal? I mostly use the GUI version anyway, but I'm curious as to what difference it makes.

**Comment by d12frosted** [comment]
`(cl-rotatef mac-command-modifier mac-option-modifier)` does basically the same. Are you sure that `osx-swap-option-and-command` is set to non-nil value? 

Depending on the terminal emulator it might now work. Didn't test any other rather than Terminal.app, but as many other macOS applications it captures keybindings like `cmd+x` (cut), so it's not propagated further.

P. S. I also use cmd as meta in graphical. :smile_cat: 

P. P. S. :thinking: forgot to click on 'comment' button.

**Comment by d12frosted** [comment]
I've searched in your emacs configurations and I don't see that you set `osx-swap-option-and-command` to `t`. 

https://github.com/t-hart/.emacs.d/search?utf8=%E2%9C%93&q=%22osx-swap-option-and-command%22&type=

**Comment by t-hart** [comment]
Yeah, I don't think I've touched the `osx-swap-option-and-command` variable  previously. It doesn't even show up when running `C-h v`. 

As for the terminal emulators, I tried with Alacritty now, and while it doesn't seem to capture the keybinding, it doesn't register the modifier, so `M-x` comes through  as `x` it seems. Don't know why, but I never really use it in the terminal, so it's not a big deal. Plus there's always `ESC x` as a backup.

Anyway, thanks for being so friendly and responsive! 😄 The application seems to be working just how I want it now.

**Comment by d12frosted** [comment]
> Alacritty

Never used it before. And your experience only supports the idea of not touching modifiers in terminal :smile_cat: As far as I remember, Terminal.app by default even doesn't send `option` key as `meta`. You have to change the settings. 

> Anyway, thanks for being so friendly and responsive! smile The application seems to be working just how I want it now.

My pleasure :smile_cat: I am glad that it works as you want it to work.

**Comment by jml** [comment]
👋 Came across this ticket and now have the following snippet in [my emacs config](https://github.com/jml/dotfiles/blob/main/emacs/config.d/06-macos.el):

```elisp
(when (and (eq system-type 'darwin) (display-graphic-p))
  (cl-rotatef mac-command-modifier mac-option-modifier))
```

Unfortunately, the option key is now interpreted by Emacs as super. This mean when I want to write £, I instead get `s-3`.

Any idea how I can change this?

Thanks so much for this great emacs build!

**Comment by thomasheartman** [comment]
Hey, @jml! 🙋🏾  That's interesting. I can't remember whether that happened to me or not, but I don't _think_ so. I don't think rotating the command and option modifiers _should_ cause that either, but I may very well be wrong on that one 😅  But I haven't used macOS for the past six months or so, so can't really offer much more here, I'm afraid 🤷🏾

**Comment by jml** [comment]
This is what I do now:

```elisp
(when (and (eq system-type 'darwin) (display-graphic-p))
  (setq mac-command-modifier 'meta)
  (setq mac-option-modifier 'option))
```

It mostly works, but the problem is that if I launch emacs from the command-line, `display-graph-p` is `nil`, and so the body doesn't execute. 

I guess what I want is for `mac-command-modifier` and `mac-option-modifier` to be set differently depending on whether the currently selected frame is a terminal frame or a graphical one. I have not been able to find the right hook for that.

**Comment by thomasheartman** [comment]
I'm not entirely sure I understand what you want. Why do you want to set the command and option modifiers differently depending on whether you're  in a terminal or not? Couldn't you just always swap them or would that break something?
