### ISSUE TITLE
DPI Issue in non-retina external monitor in latest big sur

### ISSUE THREAD

**Issue by jesse23** [d12frosted/homebrew-emacs-plus#315]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

With command below install is fine but the dpi is wrong in the non-retina monitor:

![image](https://user-images.githubusercontent.com/643912/108433098-6c309380-7213-11eb-8599-c3037ab51512.png)

## What happened (include command output)

<pre>
$ brew install emacs-plus@28 --with-native-comp --with-xwidgets --with-ctags --with-mailutils --with-modern-alecive-flatwoken-icon
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config

</pre>

## Output of `brew doctor`

<pre>
$ brew doctor

</pre>

**Comment by jesse23** [comment]
Mac OS Version:
![image](https://user-images.githubusercontent.com/643912/108435340-3ab9c700-7217-11eb-9d89-ab96ea9bd98c.png)

xcode-select --version:
![image](https://user-images.githubusercontent.com/643912/108435457-794f8180-7217-11eb-861c-50b4dbbe844d.png)

**Comment by d12frosted** [comment]
Hey,

Are you using multiple monitors (e.g. macbook and external monitor) or single non-retina monitor? Can you please try to start emacs while only non-retina monitor is active? 

I don't have any external monitors, so can't test it. In general, I believe this issue is not related to `emacs-plus` (you can confirm it by installing without any additional options, especially without xwidgets and native-comp which are highly experimental), so you might get better luck asking on r/emacs, emacs mailing list or irc.

**Comment by daviderestivo** [comment]
@jesse23 @d12frosted this issue has been already fixed in emacs upstream. Please have a look to this comment https://github.com/daviderestivo/homebrew-emacs-head/issues/92#issuecomment-781978437

**Comment by jesse23** [comment]
Thank you @d12frosted @daviderestivo  I will try to rebuild today or tomorrow and see.

**Comment by d12frosted** [comment]
@daviderestivo cool! Good to know.
