### ISSUE TITLE
pdf-tool HiDPI support doesn't work in emacs-plus

### ISSUE THREAD

**Issue by lyndondrake** [d12frosted/homebrew-emacs-plus#334]
pdf-tools has the option to render high DPI images of PDF pages by `(setq pdf-view-use-scaling t)`. This works fine in the emacs-mac port, but not in emacs-plus.

Any thoughts on what would need to be pulled into emacs-plus to make this work? (I'm using the @28 branch)

**Comment by d12frosted** [comment]
Hey @lyndondrake 

Nothing has changed in this regards since our [last conversation][1].

> But then there is `emacs-mac`, which is a beefed version of GNU Emacs specially for macOS. While it is GUI-friendly (aka good scroll support, fonts, **high resolution inline images**, etc)

I suspect that in order to get similar result we need to change rendering like `emacs-mad` did, which is a huge change and I am not in favour of it, because the goal of `emacs-plus` is to be a `homebrew` formula for GNU Emacs, and sticking to GNU Emacs as close as possible. But in case there is a trivial change in GNU Emacs codebase, I will gladly accept a patch.

Meanwhile, unfortunately, its a `wontfix`. 

[1]: https://github.com/d12frosted/homebrew-emacs-plus/issues/269#issuecomment-716106937

**Comment by lyndondrake** [comment]
Aargh, I'm *super* sorry for duplicating this. My memory must be going in my old age…

I'll see if there's a simple way to get this into GNU Emacs. I prefer your formula in general, not least because I'm happily using the native compilation and Emacs 28, which isn't available in `emacs-mac` — plus `emacs-mac` has odd little bugs (helm buffers don't display until I scroll through an item, for example).

**Comment by d12frosted** [comment]
No worries 😸 I understand that this is a confusing matter. 

> I prefer your formula in general, not least because I'm happily using the native compilation and Emacs 28,

Happy to hear that. Please not that the latest commits from native comp branch are broken, so if your installation works, do not upgrade/reinstall it! See https://github.com/d12frosted/homebrew-emacs-plus/issues/333

> 'll see if there's a simple way to get this into GNU Emacs. 

Cool, looking forward your findings.
