### ISSUE TITLE
Natural title bar has bad behavior in emacs-28

### ISSUE THREAD

**Issue by quarkquartet** [d12frosted/homebrew-emacs-plus#369]
I installed emacs-28 in my laptop on MacOS Big Sur. But the title bar seems to be different from before:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/26316540/125126679-73c0de00-e0c9-11eb-8eea-b90b856bbaa8.png">
Look at the title bar: the font is dark even on a dark theme, which is not the case for emacs-27.2. And the font is not at the middle of title-bar.

I'm using doom-emacs configuration. I'm not sure whether this is a problem of doom or emacs-plus. But everything is OK on emacs-27.

Any hint about this?

**Comment by d12frosted** [comment]
Could you please share repro steps? Also would be really helpful to:

1. Test if this happens when you start 'clean' Emacs via `emacs -Q`.
2. Test if that happens with `brew cask install emacs` (or whatever command brew changed to).

The problem may be in Doom Emacs, `emacs-plus`, your configs or Emacs itself. Let's narrow the source :)

**Comment by quarkquartet** [comment]
Hello.
- I tried `emacs -Q`. This plot is the result:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/26316540/125173073-1d1bd880-e18b-11eb-8089-5eba4d5484d7.png">
If I load a dark theme, say, `tango-dark`, it behave like this:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/26316540/125173088-3a50a700-e18b-11eb-8794-48312083b7f4.png">

 - I tried to remove my personal doom customization. The problem still exists.

- I tried `brew install --cask emacs`, which gives a emacs-27.2. The behavior is what I expect:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/26316540/125173560-0460f200-e18e-11eb-9e76-5503a800819e.png">

**Comment by d12frosted** [comment]
> I tried brew install --cask emacs, which gives a emacs-27.2. The behavior is what I expect:

Is there a way to install Emacs 28 via cask?

**Comment by quarkquartet** [comment]
> > I tried brew install --cask emacs, which gives a emacs-27.2. The behavior is what I expect:
> 
> Is there a way to install Emacs 28 via cask?

I do not think so. `brew install --cask emacs@28` does not work. If google for brew cask emacs, the website shows the current release is 27.2

**Comment by elken** [comment]
Does the following snippet help?

```elisp
(add-to-list 'frameset-filter-alist '(ns-transparent-titlebar . :never))
(add-to-list 'frameset-filter-alist '(ns-appearance . :never))
```

**Comment by quarkquartet** [comment]
> Does the following snippet help?
> 
> ```emacs-lisp
> (add-to-list 'frameset-filter-alist '(ns-transparent-titlebar . t))
> (add-to-list 'frameset-filter-alist '(ns-appearance . dark))
> ```
> 
> Or [this](https://github.com/purcell/ns-auto-titlebar) package?

I tried both. None of them works. Sorry.

**Comment by thinkiny** [comment]
same thing happend here

**Comment by thinkiny** [comment]
i found a solution:  change the system-appearance.patch:89
```
FRAME_NS_APPEARANCE (f) = ns_appearance_dark_aqua;
```
to
```
FRAME_NS_APPEARANCE (f) = ns_appearance_vibrant_dark;
```

result:
<img width="1917" alt="Screen Shot 2021-08-25 at 2 08 07 PM" src="https://user-images.githubusercontent.com/5935030/130735691-67f4b33e-2580-483f-a7bb-2df277c02765.png">

**Comment by elken** [comment]
![image](https://user-images.githubusercontent.com/2872862/131352255-bd93d34f-cbef-4c75-8c30-9cfb545d93b4.png)

Above behaviour using a light theme with global dark theme enabled, I'm wondering if that's the issue.

I can attempt it myself if need be, but I would say the patch should detect "global" light/dark mode and use either `ns_appearance_dark_aqua` or `ns_appearance_aqua`

**Comment by elken** [comment]
![image](https://user-images.githubusercontent.com/2872862/131352827-0c9840e0-1e1a-478e-8031-5ccade428b24.png)

Above behaviour is light theme on global macos dark mode. Looks like the feature check only accounts for the global macos setting, not emacs itself.

**Comment by ngquerol** [comment]
Hello all!

First, apologies for the delay, just came back from vacation 😄 

@d12frosted: @elken is correct, the conditional is here to use the appropriate `NSAppearance` depending on we are running on macOS 10.14+ or not (i.e. `ns_appearance_dark_aqua` if that is the case, `ns_appearance_vibrant_dark` otherwise).

I cannot reproduce the bug on my side (and I am unfortunately running macOS Monterey). That said, @elken & @quarkquartet could you please share what does `(frame-parameters)` returns when evaluating it while the bug is visible? Namely, is `ns-transparent-titlebar` mentioned anywhere?

**Comment by elken** [comment]
> First, apologies for the delay, just came back from vacation

Everyone is allowed time off ;)

> Namely, is ns-transparent-titlebar mentioned anywhere?

![image](https://user-images.githubusercontent.com/2872862/131386731-5a534ac8-3360-473d-aa74-f742d5d61f20.png)

**Comment by ngquerol** [comment]
Does changing the `ns-appearance` frame parameter have any impact on your end?
It should update Emacs' window appearance w/ regards to the argument, i.e. `'dark` or `'light`.
It does nothing on my end, but the good news is that I know how to fix it.

In any case, it will be up to users to set proper values of  the `ns-appearance` & `ns-transparent-titlebar` frame parameters to ensure the window's title stays readable.

**Comment by elken** [comment]
No change on my end either, that makes sense though.

**Comment by ngquerol** [comment]
Great, I'll have a stab at implementing a fix tonight if possible.

**Comment by ngquerol** [comment]
Alright, the real bug here was that updating the `ns-appearance` frame parameter did not update Emacs' window appearance. That was probably due to an incorrect rebase of my changes wrt to the upstream master 😬

The updated patch is available [here](https://gist.github.com/ngquerol/33e099eceae527b368bdf196c95d1ba3).

@elken, @quarkquartet & @d12frosted please test it if possible, and if everything seems good I'll make a PR to update the patches in this repo.

**Comment by elken** [comment]
@ngquerol Patch seems to resolve it on my end :)

- Dark theme, Dark macos 
![image](https://user-images.githubusercontent.com/2872862/131628054-359426e9-8734-4887-a84e-2ec108b19a1e.png)

- Light theme, Dark macos 
![image](https://user-images.githubusercontent.com/2872862/131628080-932a0caf-a093-4094-8236-0b729929b116.png)

**Comment by ngquerol** [comment]
@elken Looking at your screenshot, it seems that it is rather ´tool-bar-mode´ that is enabled?

**Comment by elken** [comment]
> @elken Looking at your screenshot, it seems that it is rather ´tool-bar-mode´ that is enabled?

Sorry yes, I get them mixed up. It's definitely disabled in config, reverting back to the previous patch it's disabled again.

**Comment by thinkiny** [comment]
I tried this patch, LGTM

> Alright, the real bug here was that updating the `ns-appearance` frame parameter did not update Emacs' window appearance. That was probably due to an incorrect rebase of my changes wrt to upstream's `master` branch 😬
> 
> The updated patch is available [here](https://gist.github.com/ngquerol/33e099eceae527b368bdf196c95d1ba3).
> 
> @elken, @quarkquartet & @d12frosted please test it if possible, and if everything seems good I'll make a PR to update the patch in this repo.

**Comment by ngquerol** [comment]
@thinkiny I take it you did not encounter the same issue as @elken regarding the toolbar?

**Comment by shaunsingh** [comment]
> ... and I think @shaunsingh was also having this issue.

yup, patch fixes it for me. I do have the same issue as @elken with toolbar-mode being forced though. I have it disabled in my config (and I believe doom should do it, by default)

**Comment by quarkquartet** [comment]
same as @shaunsingh

**Comment by ngquerol** [comment]
Alright, did some testing and it definitely has to do with how Doom does things.

I did not see the "bug" because I do not use this distribution; My configuration disables the toolbar by doing the following in `early-init.el`:

``` emacs-lisp
;; Disable most GUI widgets early on
(setq default-frame-alist '((horizontal-scroll-bars . nil)
                            (vertical-scroll-bars . nil)
                            (menu-bar-lines . 0)
                            (tool-bar-lines . 0) ;; <----- here
                            (internal-border-width . 0)
                            (height . 50)
                            (width . 95)))
```

While Doom does the following in `core/core-ui.el`, which is loaded from `early-init.el`:

``` emacs-lisp
(push '(menu-bar-lines . 0)   default-frame-alist)
(push '(tool-bar-lines . 0)   default-frame-alist) ;; <----- here
(push '(vertical-scroll-bars) default-frame-alist)
```

The code above can be found [here](https://github.com/hlissner/doom-emacs/blob/develop/core/core-ui.el#L308) in Doom's repository.

Copying this snippet directly into Doom's `early-init.el` results in the desired behavior, i.e. no toolbar upon startup.
It _seems_ `core/core-ui.el` is loaded a little too late in the init process, which could explain the fact that if you do a `C-x 5 2` to open a new frame, this one will _not_ have a toolbar, as opposed to the initial frame created upon startup.

I don't really know how to proceed further, and if the patch is really to blame for that behavior. Maybe @hlissner has an idea?

**Comment by shaunsingh** [comment]
I believe he mentioned a while back that he wants to move more things to `early-init.el` or something of that sort, so I assume it'll fix itself eventually?

**Comment by thinkiny** [comment]
> @thinkiny I take it you did not encounter the same issue as @elken regarding the toolbar?

sorry, i turn toolbar off by default

**Comment by elken** [comment]
@ngquerol If this is the case then I personally consider the patch to resolve the issue so if @d12frosted is happy I'd say PR and well done for fixing it :)
