### ISSUE TITLE
Migration to `brew cask`

### ISSUE THREAD

**Issue by heyarne** [d12frosted/homebrew-emacs-plus#41]
Is a migration to casks planned? Brew linkapps seems to be deprecated and superceded by `brew cask`.

**Comment by d12frosted** [comment]
Hey @heyarne 

Sorry for the late reply.

Since they are going to deprecate `linkapps`, I will provide cask version as well in a near future. And don't worry, I'll continue to maintain regular formula as well.

**Comment by jonbash** [comment]
Hey there, just checking what the status on this is? Would love to use a version of GUI Emacs with the natural title bar and whatnot!

**Comment by jonbash** [comment]
Hey there, just checking what the status on this is? Would love to use a version of GUI Emacs with the natural title bar and whatnot!

**Comment by deybhayden** [comment]
Taking an excerpt from https://www.emacswiki.org/emacs/EmacsForMacOS, you can fix Spotlight for emacs-plus as well:

```
Spotlight indexes symlinks to files that are treated as system files, but it doesn’t show them in the GUI. It does show aliases though, so you could just command-option-drag /usr/local/Cellar/emacs-plus/*/Emacs.app to /Applications/ from Finder
```

This is working well for me.

**Comment by pcr910303** [comment]
As this repo is already running Travis CI and building Emacs, I would appreciate if the Travis CI would build per every commit and publish the binaries to GitHub or Binary, etc... and make a cask for it.

**Comment by d12frosted** [comment]
Yes, I use travis to run builds (just to test that everything builds). Note sure that it worth deploying on every build, because I only deploy 'default' configuration, which changes only once in a while.

AFAIK, you can only provide bottles for default options, right?

Regarding cask - I don't know how to do it, actually. I remember I've read some documentation about it, but don't remember any details. If you know how to do it, please share. Or even let's do it :)

**Comment by pcr910303** [comment]
@d12frosted
Yeah, you can only provide some default options for Homebrew cask(AFAIK cask != bottles)
I’ll see the `.travis.yml` tomorrow and (hopefully) make a PR; It’s too late here (4AM) :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d12frosted** [comment]
@pcr910303 cool, let me know if you need anything

> It’s too late here (4AM) :-)

I would say that it's too early :smile_cat:

**Comment by greened** [comment]
What is the status of this?

**Comment by d12frosted** [comment]
@greened there is no update on this. If someone really wants to have cask formula, I would gladly take some help on this.

**Comment by d12frosted** [comment]
I am closing this issue as there is no interest in making this happen. I would still gladly accept cask support as a contribution, but there is no actions for me at this point of time.

**Comment by angrybacon** [comment]
Is copying the `.app` to `Applications/` still the accepted solution as of today? Am reinstalling a new machine running Ventura 13.0 and was hoping I could install all my graphical applications using `--cask` which doesn't seem supported for Emacs+

Having cask take care of the linking would check my one requirement: finding Emacs.app from Spotlight without having to copy the `.app` on every update since links don't seem to be indexed

**Comment by d12frosted** [comment]
You can copy the `.app`. As per `cask` - nothing changed. I don't have time to dig into this. If someone wants to bring it in, contributions are welcome :)

**Comment by d12frosted** [comment]
@angrybacon btw, you might be interested in [this](https://github.com/d12frosted/homebrew-emacs-plus/pull/517#issuecomment-1280867786).

**Comment by d12frosted** [comment]
Well. Suddenly we have cask support. See https://github.com/d12frosted/homebrew-emacs-plus?tab=readme-ov-file#pre-built-binaries-cask (cfc728d2a780ca7f365c7ceb7dea02f72b1c285d).
