### ISSUE TITLE
tab-bar-mode doesn't show the tabs bar 

### ISSUE THREAD

**Issue by Inc0n** [d12frosted/homebrew-emacs-plus#427]
I have used the following compilation flags to install `emacs-plus@28`:
```
brew tap d12frosted/emacs-plus
brew install emacs-plus@28 --HEAD --with-native-comp --with-no-frame-refocus --with-no-titlebar
```
When I enable `tab-bar-mode`, the top tabs bar doesn't show up, I suspect this may be related to one of the compilation flag that I have passed into `brew install`. My past experience on linux, was that the bar shows up at the top.
However, it is slightly costly to experiment at the moment, so I would like some expert opinions on this first.

**Comment by d12frosted** [comment]
Hey

I am on Emacs 29 and `tab-bar-mode` works well even `--with-no-titlebar`. Not a user of this mode, so not sure why it happens. In order to ease the cost of testing - clone this repo and use `build` script in the root:

```
$ ./build 28
```

It will build a formula called `emacs-plus-local`, so you could switch between real installation and a testing playground.

P.S. you don't need `--HEAD` with `emacs-plus@28`. It has no meaning here.

**Comment by Inc0n** [comment]
I have just tried out emacs29, with the following:
```
brew install emacs-plus@29 --with-native-comp --with-no-titlebar
```

**Comment by Inc0n** [comment]
I have just tried out emacs29,`tab-bar-mode` worked fine, even with `--with-no-titlebar` 
hmmm
