### ISSUE TITLE
Could not install with emacs-plus@28 --with-native-comp

### ISSUE THREAD

**Issue by minhluuquang** [d12frosted/homebrew-emacs-plus#474]
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

install emacs-plus@28 --with-native-comp  

## What happened (include command output)

<pre>
$ brew install emacs-plus --with-native-comp
</pre>

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://gcc.gnu.org/git/?p=gcc.git;a=patch;h=fabe8cc41e9b01913e2016861237d1d99d7567bf
Already downloaded: /Users/macintosh/Library/Caches/Homebrew/downloads/8bf155b1b8aed3fc0d3d3ec2e4e1a4560b424fa44f327212e9e1d6915f68be82--gcc.git-fabe8cc41e9b01913e2016861237d1d99d7567bf.patch
Error: emacs-plus@28: SHA256 mismatch
Expected: 9d3c2c91917cdc37d11385bdeba005cd7fa89efdbdf7ca38f7de3f6fa8a8e51b
  Actual: c1dd23ab9b99971f718bc5e1b4b8b65ce1e2eced719a434eb15abfef80d8f7b7
    File: /Users/macintosh/Library/Caches/Homebrew/downloads/8bf155b1b8aed3fc0d3d3ec2e4e1a4560b424fa44f327212e9e1d6915f68be82--gcc.git-fabe8cc41e9b01913e2016861237d1d99d7567bf.patch
To retry an incomplete download, remove the file above.
  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e0295b38899d53b8ae4362964bfea5422b813d6e
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: //opt/homebrew
HOMEBREW_REPOSITORY: //opt/homebrew
HOMEBREW_CELLAR: //opt/homebrew/Cellar
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.3.1.0.1.1648687083
Xcode: N/A
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by d12frosted** [comment]
Hey,

Looks like this a mismatch inside `gcc` formula, which is unrelated to `emacs-plus`. I found kind of relevant [commit][1] that updated `gcc` formula. I guess this error happens because there is no revision system for resources (like patches) in `brew`, so there is no way to tell `brew` that patch has changed. And since you have a cached one, `brew` uses it, but it's a wrong patch hence the error. 

Though there is one troubling thing - your error says that expected hash is `9d3c2c91917cdc37d11385bdeba005cd7fa89efdbdf7ca38f7de3f6fa8a8e51b`, which is also outdated. But your `brew config` seems pretty updated :thinking: 

Not sure if it helps, but please try the following. Update brew once more, remove offending cached patch and try to install again:

```bash
brew update
rm /Users/macintosh/Library/Caches/Homebrew/downloads/8bf155b1b8aed3fc0d3d3ec2e4e1a4560b424fa44f327212e9e1d6915f68be82--gcc.git-fabe8cc41e9b01913e2016861237d1d99d7567bf.patch
brew install emacs-plus --with-native-comp
```

[1]: https://github.com/Homebrew/homebrew-core/commit/dc8fb3f0cfdc29c0bd23e1a36706c1deb78da9af
