### ISSUE TITLE
how to CFLAGS="-DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT "?

### ISSUE THREAD

**Issue by jixiuf** [d12frosted/homebrew-emacs-plus#487]
see https://emacstalk-github-io.translate.goog/post/022/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN

the default value of max open files is 1024 which is too small for me .
I can increment it with  this patch, hope homebrew-emacs-plus can support this .

```
diff --git a/Formula/emacs-plus@29.rb b/Formula/emacs-plus@29.rb
index 87b9f0d..c25bb5c 100644
--- a/Formula/emacs-plus@29.rb
+++ b/Formula/emacs-plus@29.rb
@@ -114,6 +114,7 @@ class EmacsPlusAT29 < EmacsBase
     args << "--with-native-compilation" if build.with? "native-comp"
 
     ENV.append "CFLAGS", "-g -Og" if build.with? "debug"
+    ENV.append "CFLAGS", " -DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT "
 
     args <<
       if build.with? "dbus"
```

```
export CFLAGS="-DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT" // this does not work
```

**Comment by d12frosted** [comment]
I am not sure what to do here. I wonder why the default value is 1024. And I wonder how often people need to change it. And if there is a wider need, what value should we use? There is a limitation imposed by `brew` that makes this feature problematic — you can't have parametrised options in formula[^1]. That's why we have `--with-NAME-icon` instead of `--with-icon=NAME`. Hence we need to pick one or multiple values (if we are ready to introduce more options).

In addition, I try to limit amount of options provided by Emacs+ formula.

It's not a strong opinion, I am open to including it. My message just explains why I am hesitant.

[^1]: If that's incorrect, please let me know 🙏 I would love to simplify available options.

**Comment by jixiuf** [comment]
> what value should we use?
maybe we can get the value from `ulimit -n` or by a user defined ENV?

As an `eglot` user, I think 1024 is too small.

**Comment by danilevy1212** [comment]
As a `lsp` and `elfeed` user, this is a constant pain in the neck. 10000 would be a huge improvement.

**Comment by sebasmonia** [comment]
Thirding (?) the request for an increase. Started using macOS recently for work and hitting this somewhat often.
Using LSP + restclient.

**Comment by d12frosted** [comment]
> maybe we can get the value from ulimit -n or by a user defined ENV?

On my machine `ulimit -n` returns 256. Meaning that people might be affected in a bad way if we blindly use that value. ENV might be a good variant, but I want solution to be scalable for other options as well (e.g. icons).

After reading a little bit about it, seems like there is no real drawback in increasing this value to, say, 10000. So PR is welcome to increase it.

**Comment by d12frosted** [comment]
See https://github.com/d12frosted/homebrew-emacs-plus/pull/510 as alternative approach.
