### ISSUE TITLE
Please add a `--with-c-source` flag

### ISSUE THREAD

**Issue by offbyone** [d12frosted/homebrew-emacs-plus#548]
I would like to install this with the C source attached, so that when I look for references to variables or functions, the C source is in a predictable location. 

Looking at the installed content, I can't find any sign of it; if it's in a different location, I'm also happy to locate it from there.

Thanks for the formula in general, though!

**Comment by d12frosted** [comment]
Hey

> I would like to install this with the C source attached, so that when I look for references to variables or functions, the C source is in a predictable location.

Both `emacs-plus@29` and `emacs-plus@30` are always built from sources, and you can find the source under `$HOME/Library/Caches/Homebrew/emacs-plus@29--git/` or `$HOME/Library/Caches/Homebrew/emacs-plus@30--git/` respectively. So until released there is no need to provide any extra options here.

Released versions (e.g. `emacs-plus@28`) have `--HEAD` option which installs from git source. And that gives the same effect as with unreleased versions. Though, a slightly different version. 

In theory, we might provide an extra option to build released version from git source instead of provided `tar` files. The source will be located in the very same `$HOME/Library/Caches/Homebrew/emacs-plus@VERSION--git`. Though I would love to avoid that and provide either `--HEAD` or released version.

That being said, is `$HOME/Library/Caches/Homebrew/emacs-plus@VERSION--git` a "predictable location" for you?

P.S. Just for completeness. `brew` provides an option to build from source (`--build-from-source` or `-s` for short), which builds from source even if bottle is available. I do not provide bottles anymore.
