### ISSUE TITLE
Toggle titlebar ("undecorated frame") of the current frame to deal with macOS "notch"

### ISSUE THREAD

**Issue by aguynamedben** [d12frosted/homebrew-emacs-plus#588]
**On my monitor:** I hide the macOS "notch" using TopNotch, so most of the time I want an undecorated frame.
**On my laptop:** `toggle-frame-maximized` doesn't deal with the "notch" well, so I want a decorated frame

ChatGPT 4 helped me sort out this helpful function, and I'm so amazed I thought I'd post it here as a faux feature request because it seems like something Emacs+ could provide.

Toggle on/off titlebar of current frame, maximize afterward
```elisp
(defun toggle-undecorated-frame ()
  "Toggle the 'undecorated' parameter and frame maximized state for the current frame."
  (interactive)
  (let* ((undecorated-value (frame-parameter nil 'undecorated))
         (new-value (not undecorated-value)))
    (set-frame-parameter nil 'undecorated new-value)
    (toggle-frame-maximized))
  (message "Undecorated frame setting and maximized state toggled."))
```

Toggle on/off titlebar of current frame, don't maximize

```elisp
(defun toggle-undecorated-frame ()
  "Toggle the 'undecorated' parameter for the current frame."
  (interactive)
  (let* ((undecorated-value (frame-parameter nil 'undecorated))
         (new-value (not undecorated-value)))
    (set-frame-parameter nil 'undecorated new-value))
  (message "Undecorated frame setting toggled."))
```

Feel free to close if this is just noise and shouldn't be committed to this repo, but maybe it will be helpful for someone else dealing with the macOS notch and `toggle-frame-maximized`.

**Comment by d12frosted** [comment]
Hey @aguynamedben 

Highly appreciate the tip. I don't think it makes sense to commit these Lisp functions to Emacs+ simply because Emacs+ is just a formula of GNU Emacs for Homebrew. That being said, we do apply some patches to Emacs code base, but only to C/Objective-C code that can't be applied by users otherwise. Adding these two little functions to `init.el` is trivial, while figuring out where to put them in Emacs code base, how to name and how to provide various configurations (e.g. should it maximise or not?) and maintaining them is not that trivial 😅 So IMO it's better to put these helpers in `init.el` 💪 

Anyways, thank you for sharing, hope someone will find it useful 💯

**Comment by aguynamedben** [comment]
@d12frosted 👍 totally makes sense
