### ISSUE TITLE
How do I get background alpha?

### ISSUE THREAD

**Issue by summeremacs** [d12frosted/homebrew-emacs-plus#605]
Hi! I've been using d12frosted since about a month and I love it. I'm on the 30 version right now. However, I noticed that background alpha isn't working? Is it just me?

https://www.emacswiki.org/emacs/TransparentEmacs <-- Link for how to enable it

`(set-frame-parameter nil 'alpha-background 70)

(add-to-list 'default-frame-alist '(alpha-background . 70))`

It doesn't give any errors when I eval it, but it doesn't do anything either. I'm wondering if I am doing something wrong? Please let me know. Thanks!

**Comment by d12frosted** [comment]
Hey,

As far as I can tell, the article describes transparency for X/Wayland. It doesn't work in macos build.

To my knowledge, GNU Emacs doesn't support transparent background in macos GUI.

> It doesn't give any errors when I eval it,

Because there is nothing to error on. It just the underlaying system ignores (e.g. doesn't interpret) the `alpha-background` param. 

P.S. Kind of related - https://github.com/d12frosted/homebrew-emacs-plus/issues/541.

**Comment by summeremacs** [comment]
tysm! I must have missed that. I'm sorry. I guess I'll just live without it. It's not that big of a deal because mostly I use it in full screen mode anyway. It was just for when I sometimes use it in 2/3 screen or 1/2 screen. But I've lived this long without it and happily so I'm not gonna gripe over it. 🙃

I did have another issue I was gonna post but I'll do that in another report. ty again!

**Comment by ypytomets** [comment]
Maybe related https://lists.gnu.org/archive/html/emacs-devel/2024-06/msg01007.html

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=71850
