### ISSUE TITLE
Play sound

### ISSUE THREAD

**Issue by dertuxmalwieder** [d12frosted/homebrew-emacs-plus#616]
I would like to be able to play sound over Emacs's internal `play-sound` functionality. Emacs Plus does not let me do that by default:

```
play-sound: This Emacs binary lacks sound support
```

**Comment by christianromney** [comment]
I have a (possibly) related question. I would love to give emacs access to the microphone so I can use whisper.el. Looking [at this commit](https://github.com/d12frosted/homebrew-emacs-plus/commit/627d2dffa5520b74a4eb6b0efbcc453f76ba2f53) it seems you've at least experimented with Camera access. Is this really as simple as adding a plist entry? The Apple Developer docs on the [Hardened Runtime](https://developer.apple.com/documentation/security/hardened_runtime) make it seem like some compile-time XCode tomfoolery is required. I would love to contribute, but I would need some guidance since I am not a Mac dev. Any suggestions?

**Comment by d12frosted** [comment]
@christianromney I've merged your PR (thanks for it 🙏 ). In the case of `play-sound` I am pretty sure it's not about permission, but rather about implementation. Need to check if there is an implementation of this function for macos. 

btw, @dertuxmalwieder did you find solution?

**Comment by dertuxmalwieder** [comment]
I’m afraid not. The best thing I could find was this: https://github.com/leoliu/play-sound-osx

**Comment by ejmg** [comment]
with respect to `play-sound`, emacs [does not.](https://github.com/emacs-mirror/emacs/blob/c85294a6132e57bc0d24e39589b2c6163c11ca87/src/sound.c#L24-L94)

**Comment by d12frosted** [comment]
Closing this issue as out of scope of this project. Ideally it should be implemented in the upstream. Yet knowing darwin not being focus for upstream, I am still open to ideas.
