### ISSUE TITLE
Application is not linked out of box

### ISSUE THREAD

**Issue by michaelssingh** [d12frosted/homebrew-emacs-plus#618]
OK,  looks like I might have filled that out correct.

One of the immediate issues that I noticed after the installation was that there wasn't an icon for Emacs in the Application Launcher or Spotlight

On my system trying to create a link in /Application resulted in the following error:
`ln -s /opt/homebrew/opt/emacs-plus@29/Emacs.app /Applications`
Gave an error about read-only file-system

This how I managed to get the icon to appear in the application launcher but it doesn't show up in spotlight
`ln -s /opt/homebrew/opt/emacs-plus@29/Emacs.app /System/Volumes/Data/Applications/Emacs.ap`

When launching Emacs from here the Application Launcher,  why don't we have it call `emacsclient -a emacs` to connect to server that is already running by default.

**Comment by d12frosted** [comment]
Hey @michaelssingh 

Regarding the spotlight/finder - it's a known issue. There were several related issues/prs - #41, #517, #488, #324. I acknowledge that the current instructions are problematic and they do not work. AFAIU the Homebrew-recommended way for apps to appear in applications folder/spotlight/whatever is to use cask (see #41). Unfortunately, I don't have enough time and motivation to tackle this.

I would really appreciate someone to either (a) actually figure out the best way to link the app and update instructions or (b) figure out how to provide cask. 

Regarding the `.app` wrapper for `emacsclient`. https://github.com/d12frosted/homebrew-emacs-plus/issues/398 describes some ways to achieve this. Emacs+ could provide some wrapper out of box (although the question about linking strikes again), but it's low on my priority list (unfortunately).

> When launching Emacs from here the Application Launcher, why don't we have it call emacsclient -a emacs to connect to server that is already running by default.

Specifically the idea of `Emacs.app` to launch `emacsclient` - I am pretty sure that's not what everyone would like to have. Not everyone run the server and more importantly - not everyone want to run the server. That's why I don't touch that 😸

**Comment by michaelssingh** [comment]
> Hey @michaelssingh 

> Regarding the `.app` wrapper for `emacsclient`. #398 describes some ways to achieve this. Emacs+ could provide some wrapper out of box (although the question about linking strikes again), but it's low on my priority list (unfortunately).
> 
> > When launching Emacs from here the Application Launcher, why don't we have it call emacsclient -a emacs to connect to server that is already running by default.
> 
> Specifically the idea of `Emacs.app` to launch `emacsclient` - I am pretty sure that's not what everyone would like to have. Not everyone run the server and more importantly - not everyone want to run the server. That's why I don't touch that 😸

`emacsclient` has the `-a` flag which specifies a fallback editor to use if the server is not running

Here's a `fish` function that does this
```
function e -d "Starts a GUI emacsclient in a new frame"
  emacsclient -c -a vim $argv > /dev/null &
end
```

**Comment by d12frosted** [comment]
Vim is definitely not a good fallback 😹 Not because it's vim, but because we are talking about GUI apps. Ok, we could try to run emacs with GUI instead, but then... what if I want to start a new Emacs instance not connected to a running server? IMO it's better to have `Emacs.app` and `EmacsClient.app` separately just the way we have it in CLI. This way user gets expected behaviour instead of a 'magical' (or a DWIM) one.

**Comment by allen-liaoo** [comment]
Any updates on this or instructions on how to make .app appear in /Applications?

**Comment by ryankhart** [comment]
> Any updates on this or instructions on how to make .app appear in /Applications?

Right there with you. I wish it did this automatically as well.

However, if you were to `brew reinstall emacs-plus@29`, for example, you can see a commandline instruction to copy and paste a line that starts with `osascript -e 'tell applications "Finder" to make alias [...]` and run that command after reinstalling.

**Comment by verhovsky** [comment]
This no longer works on macOS 15.3.1. The alias shows up in Spotlight, but it's at the very bottom under "Other" and Spotlight never learns to suggest it when you type "emacs", much less "e".
