### ISSUE TITLE
native-comp is enabled by default in emacs 30, Please add option --with-native-compilation=no

### ISSUE THREAD

**Issue by liuyinz** [d12frosted/homebrew-emacs-plus#635]
A clear and concise description of what the desired feature is. If the feature
request is adding existing patch, please share the link to it.

**Comment by d12frosted** [comment]
AFAIU, it's not enabled by default. By default it checks if you have libgccjit installed, and if yes, Emacs will be compiled with native compilation feature. Since I've switched back to super env, your custom installed packages should not leak anymore, so no changes are necessary.

Let me know if the issue still persists,
