### ISSUE TITLE
Launching from the Emacs.app doesn't set $EMACS environment variable.

### ISSUE THREAD

**Issue by CupricWolf** [d12frosted/homebrew-emacs-plus#69]
The Prezto configuration manager for zsh has a feature that can automatically start tmux when a new shell is created. Before it does this though it checks to see if the shell was created in a tmux window or by an editor. It does this through the $EMACS, $VIM, or $TMUX variables. If any of those are set Prezto won't try to use tmux.

When I launch emacs-plus from a shell it sets the $EMACS variable and I am able to use the shell both in emacs configurations (like in part of the spacemacs startup process)  and in shell mode. But if I use the Emacs.app in the Cellar $EMACS is not set and Prezto proceeds to start tmux.

For example when starting spacemacs I get the following warning about halfway through my packages getting loaded.

```
Error (use-package): exec-path-from-shell/:config: Non-zero exit code from shell /usr/local/bin/zsh invoked with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s\\000__RESULT' \"${PATH-5b357592b274f24cd652d4aebc6827a9}\" \"${MANPATH-5b357592b274f24cd652d4aebc6827a9}\"").  Output was:
"open terminal failed: not a terminal
"
```

**Comment by d12frosted** [comment]
Hey @CupricWolf,

It seems that your issue is out of scope for this project. AFAIK, Emacs doesn't set `$EMACS` variable, and I bet that in your case it's being set by some Elisp program. 

> For example when starting spacemacs I get the following warning about halfway through my packages getting loaded.

You should report it to the Spacemacs issue tracker. Or `exec-path-from-shell`. As it's a problem of configuration. 

A quick search didn't help to find any useful advice. 

P. S. Closing this issue as it's not related to `emacs-plus` itself, but your configurations. If you don't agree, let me know.

**Comment by MNicole1** [comment]
Ok. Thanks for the feedback
