### ISSUE TITLE
brew services stop doesn't work

### ISSUE THREAD

**Issue by deybhayden** [d12frosted/homebrew-emacs-plus#72]
Hi there! Thanks for the great Emacs macOS build! I noticed this earlier, but if I start the service, and then later want to restart the server, I have to kill everything by hand, because stop/restart don't seem to be working?

<img width="1362" alt="screen shot 2018-03-23 at 12 43 04 am" src="https://user-images.githubusercontent.com/877908/37813525-6ef2198a-2e33-11e8-91f6-3da927a39d4a.png">

**Comment by d12frosted** [comment]
I am sorry for late reply. Somehow I missed your message :(

Never really used `services` command of `brew`, so didn't see this issue before. I am in travel mode right now, so can't really check it, will do once I am back.

In case you already figured that out, please let me know 😸

**Comment by antonalekseev** [comment]
Actually, current issue goes beyond `homebrew services` infrastructure. Process which is running under supervision of `launchd` isn't supposed to _daemonise_ itself, as per `launchd.plist(5)`:

> A daemon or agent launched by `launchd` MUST NOT do the following in the process directly launched by `launchd`:
> * Call `daemon(3)`.
> * Do the moral equivalent of `daemon(3)` by calling `fork(2)` and have the parent process `exit(3)` or `_exit(2)`.

Therefore current (version 25.3) behaviour of `emacs --daemon` is not compatible with `launchd`. 

Good news is that the option `--new-daemon` which instructs process to stay in foreground was introduced in https://github.com/emacs-mirror/emacs/commit/36b99556dea23f17d5598bbed366e7201eec9fbb (was renamed to `--fg-daemon` later in https://github.com/emacs-mirror/emacs/commit/75b849294656fd92e77a2a6281ff4dceaaa38475).

Otherwise, one should implement wrapper script  to be called from `.plist` which would catch `SIGTERM` from `launchd` and then would shutdown emacs instance with the explicit command, e.g. `emacsclient -e "(save-buffers-kill-emacs)"` or would send a signal to `PID` from `emacsclient -e "(emacs-pid)"`.

Considering #73, the former option seems more reasonable.

**Comment by d12frosted** [comment]
@antonalekseev thanks for the input!

I'd wait for 26.1 and switch to `--fg-daemon` like you did in https://github.com/antonalekseev/homebrew-tap/commit/de73bbb02c79c6a776a33b9a02ee57fe92147a52.

**Comment by gnzlbg** [comment]
@antonalekseev do you have a dock app that's able to connect to this daemon ? If so, could you share how you are achieving that ? 

Right now, I am creating a bash script that calls emacsclient, and have bundled that into an App. However, when I call the App it starts another `Emacs.App` that connects to the daemon, and when I fully close this app, the daemon is closed as well, which kind of defeats the point.
