### ISSUE TITLE
[Feature request]: Incorporate emacs-lsp's patches

### ISSUE THREAD

**Issue by i-am-linja** [d12frosted/homebrew-emacs-plus#722]
### Feature request description

emacs-lsp had a [fork](https://github.com/emacs-lsp/emacs) of Emacs to improve concurrency, and reportedly gained _significant_ speed from this. The fork has since been abandoned, but their work may be adaptable, especially for only a single target.

**Comment by d12frosted** [comment]
Hey @i-am-linja . Thanks for sharing the link.

Considering that the fork is abandoned and is no longer maintained I don't see any reason to include any patches from that fork to Emacs+ (which is just a brew formula for GNU Emacs and nothing more).

We do have experiments in Emacs+, but in some cases it was a mistake to include them and I am working towards getting rid some of them (you can see that not everything available for Emacs 29 is available for Emacs 31).

That being said I am all for helping with adoption of new features that are on the way to get into master. But these features need active maintainers and support, otherwise it's going to be a pain for me as I don't have much capacity.

If Emacs-LSP brings significant performance boost, I am pretty sure it must be part of GNU Emacs and patches must be sent to the upstream, not here.

**Comment by d12frosted** [comment]
Oh btw, if you want to toy around with that fork while still getting "comfort" of brew formula, you can `brew edit emacs-plus@30` and change the following line:

https://github.com/d12frosted/homebrew-emacs-plus/blob/6f099bb618334885f509c907efc9a0e0e4257ac5/Formula/emacs-plus%4030.rb#L82

And then install `emacs-plus@30` normally.
