### ISSUE TITLE
[Build Failure]: Linux

### ISSUE THREAD

**Issue by uliw** [d12frosted/homebrew-emacs-plus#747]
### Version

emacs-plus@30

### Make sure to follow these steps before submitting the issue

- [ ] run `brew update` and try to reproduce the issue again
- [ ] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ ] try to reproduce your issue without any custom options to the formula

### What happened?

<pre>
brew install d12frosted/emacs-plus/emacs-plus@30 --with-x11 --with-native-comp --with-imagemagick --without-cocoa
</pre?

<details>
  <summary>Command output</summary>
  <pre>

  ==> Fetching d12frosted/emacs-plus/emacs-plus@30
==> Downloading https://alpha.gnu.org/gnu/emacs/pretest/emacs-30.0.92.tar.xz
############################################################################################################################################# 100.0%
==> Installing emacs-plus@30 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
==> Applying system-appearance.patch
==> Applying round-undecorated-frame.patch
==> ImageMagick PKG_CONFIG_PATH: 
/home/linuxbrew/.linuxbrew/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --disable-silent-rules --enable-locallisppath=/home/linuxbrew/.linuxbrew/share/emacs/site-lisp --infodir=/home/linuxbrew/.linuxbrew/
Error: An exception occurred within a child process:
  NameError: uninitialized constant Formulary::FormulaNamespaceed0da82beb322f6c49ad12bd60f276ae70bb818aa18ea780f2e8ad4e2063af4b::EmacsPlusAT30::MacOS

  </pre>
</details>

### brew doctor output

Your system is ready to brew.

### brew config output

OMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 5 days ago
Core tap JSON: 01 Nov 13:38 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 3.3.5 => /usr/bin/ruby.ruby3.3
CPU: 24-core 64-bit zen3
Clang: N/A
Git: 2.46.1 => /bin/git
Curl: 8.10.1 => /bin/curl
Kernel: Linux 6.11.2-1-default x86_64 GNU/Linux
OS: openSUSE Tumbleweed
Host glibc: 2.40
/usr/bin/gcc: 14.2.0
/usr/bin/ruby: 3.3.5
glibc: N/A
gcc@11: N/A
gcc: 14.2.0_1
xorg: N/A

### Any extra information

Thanks for looking into this

**Comment by mishok13** [comment]
Ran into the same issue, which I believe is related to [this patch](https://github.com/Homebrew/brew/pull/18388/files#diff-7e7f927b5a956040b1e5cd4fc54be50d29778145d2cfd57cd1598ed3823e95c0L53-L119) that landed in Homebrew 4.4.0. Seems that `MacOS` variable is now undefined (instead of being a dummy var) and proper check should be done with `OS.mac? && MacOS.version <= :mojave` in all formulas.

**Comment by mishok13** [comment]
@d12frosted would there be any interest in the fix for this? I have a [PR in the works](https://github.com/mishok13/homebrew-emacs-plus/pull/1/files) in my fork, however I don't know if you'd be willing to extend GH Actions to also cover linuxbrew. I'm happy to strip down the patch to just the fix while leaving CI as-is if that's what you'd prefer.

**Comment by d12frosted** [comment]
@mishok13 I am absolutely in favour of fixing the build for Linux + including one test. Maybe only `emacs.yml` - I will clean the irrelevant options from there (I mean, build from source is fine in some cases, but I don't care about icon anymore as we have separate tests from that).
